# Configure service
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  selector:
    app: catalogapi-pod
  ports:
  - port: 8080
    targetPort: 80
  #type: LoadBalancer # use LoadBalancer if you want to accesss out side of pod